DROP TABLE IF EXISTS EMPRESA_INTERESSADA;
DROP TABLE IF EXISTS EMPRESA_VENDEDORA;

CREATE TABLE EMPRESA_VENDEDORA
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    quant_disponivel INT NOT NULL,
    quant_vendida INT NULL
);

INSERT INTO EMPRESA_VENDEDORA (nome, quant_disponivel, quant_vendida)
VALUES ('Empresa P', 4000 , 0),
       ('Empresa O', 4000 , 0),
       ('Empresa Do Caram', 1000 , 0);

CREATE TABLE EMPRESA_INTERESSADA
(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    quant_requerida INT NOT NULL,
    valor DOUBLE NOT NULL,
    vendedora_id BIGINT,

    FOREIGN KEY (vendedora_id) REFERENCES EMPRESA_VENDEDORA (id)
);
